// Developer Master Salt (Must match public/license-generator.html)
const DEV_SECRET_SALT = 'NKLIAT_FREIGHT_2026_SECURE_DEV_KEY_!#99X';
const LICENSE_STORAGE_KEY = 'nkliat_license_info_v1';
const MACHINE_ID_KEY = 'nkliat_machine_unique_id';

export interface LicenseInfo {
  isLicensed: boolean;
  licenseType: 'trial' | 'annual' | 'lifetime' | 'unlicensed';
  clientName: string;
  licenseKey: string;
  activatedAt: string;
  expiresAt: number; // 0 for lifetime
  expiresDateFormatted: string;
  daysRemaining: number;
  isExpired: boolean;
  machineId: string;
}

// Helper to hash string via subtle crypto
async function sha256(message: string): Promise<string> {
  const msgBuffer = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
}

export class LicenseService {
  private static instance: LicenseService;

  private constructor() {}

  public static getInstance(): LicenseService {
    if (!LicenseService.instance) {
      LicenseService.instance = new LicenseService();
    }
    return LicenseService.instance;
  }

  // Generate or retrieve persistent Hardware / Machine ID
  public getMachineId(): string {
    let id = localStorage.getItem(MACHINE_ID_KEY);
    if (!id) {
      // Build a distinct recognizable Machine ID
      const randGroup = () =>
        Math.floor(1000 + Math.random() * 9000)
          .toString(16)
          .toUpperCase()
          .padStart(4, '0');
      id = `TRK-${randGroup()}-${randGroup()}-${randGroup()}`;
      localStorage.setItem(MACHINE_ID_KEY, id);
    }
    return id;
  }

  // Get current active license state
  public getCurrentLicense(): LicenseInfo {
    const machineId = this.getMachineId();
    const raw = localStorage.getItem(LICENSE_STORAGE_KEY);

    if (!raw) {
      return {
        isLicensed: false,
        licenseType: 'unlicensed',
        clientName: '',
        licenseKey: '',
        activatedAt: '',
        expiresAt: 0,
        expiresDateFormatted: 'غير مرخص',
        daysRemaining: 0,
        isExpired: true,
        machineId,
      };
    }

    try {
      const data = JSON.parse(raw);
      const now = Date.now();
      const isLifetime = data.licenseType === 'lifetime' || data.expiresAt === 0;
      const isExpired = !isLifetime && data.expiresAt < now;
      const daysRemaining = isLifetime
        ? 9999
        : Math.max(0, Math.ceil((data.expiresAt - now) / (1000 * 60 * 60 * 24)));

      return {
        isLicensed: !isExpired,
        licenseType: data.licenseType || 'unlicensed',
        clientName: data.clientName || 'المستخدم',
        licenseKey: data.licenseKey || '',
        activatedAt: data.activatedAt || '',
        expiresAt: data.expiresAt || 0,
        expiresDateFormatted: isLifetime
          ? 'دائم مدى الحياة'
          : new Date(data.expiresAt).toISOString().split('T')[0],
        daysRemaining,
        isExpired,
        machineId,
      };
    } catch {
      return {
        isLicensed: false,
        licenseType: 'unlicensed',
        clientName: '',
        licenseKey: '',
        activatedAt: '',
        expiresAt: 0,
        expiresDateFormatted: 'خطأ في قراءة الترخيص',
        daysRemaining: 0,
        isExpired: true,
        machineId,
      };
    }
  }

  // Activate license using key generated by Developer License Generator
  public async activateLicense(licenseKey: string, clientName: string = ''): Promise<{ success: boolean; message: string }> {
    const key = licenseKey.trim();
    if (!key.startsWith('NKL-')) {
      return { success: false, message: 'صيغة مفتاح الترخيص غير صحيحة (يجب أن يبدأ بـ NKL-).' };
    }

    try {
      const b64 = key.substring(4).replace(/-/g, '+').replace(/_/g, '/');
      // Add padding back if necessary
      const paddedB64 = b64.padEnd(b64.length + ((4 - (b64.length % 4)) % 4), '=');
      const jsonStr = atob(paddedB64);
      const payload = JSON.parse(jsonStr);

      const machineId = this.getMachineId();
      const normalizedDevice = machineId.replace(/[^A-Z0-9]/g, '');

      // Check if machine prefix matches
      if (!normalizedDevice.startsWith(payload.m)) {
        return {
          success: false,
          message: 'هذا المفتاح مخصص لجهاز آخر ولا يتطابق مع رمز هذا الجهاز الحالي.',
        };
      }

      // Check expiration timestamp
      const now = Date.now();
      const isLifetime = payload.t === 'l' || payload.e === 0;
      if (!isLifetime && payload.e < now) {
        return { success: false, message: 'مفتاح الترخيص هذا منتهي الصلاحية بالفعل.' };
      }

      const typeMap: Record<string, 'trial' | 'annual' | 'lifetime'> = {
        t: 'trial',
        a: 'annual',
        l: 'lifetime',
      };
      const licenseType = typeMap[payload.t] || 'annual';

      // Save valid license
      const licenseData = {
        licenseKey: key,
        clientName: clientName.trim() || 'المؤسسة المرخصة',
        licenseType,
        activatedAt: new Date().toISOString(),
        expiresAt: payload.e,
      };

      localStorage.setItem(LICENSE_STORAGE_KEY, JSON.stringify(licenseData));
      return { success: true, message: 'تم تفعيل ترخيص النظام بنجاح!' };
    } catch {
      return {
        success: false,
        message: 'فشل فك تشفير مفتاح الترخيص، تأكد من نسخه بشكل صحيح ودقيق.',
      };
    }
  }

  // Reset / Deactivate (for re-licensing or testing)
  public deactivate(): void {
    localStorage.removeItem(LICENSE_STORAGE_KEY);
  }
}

export const licenseService = LicenseService.getInstance();
